name: TensuraUHC
version: 1.0
main: uhc.tensuraUHC.TensuraUHC
api-version: 1.8

commands:
  host:
    description: Définit l'Host principal de la partie.
  cohost:
    description: Ajoute ou retire un Co-Host.
  lobby:
    description: Téléporte au lobby.
  revive:
    description: Ressuscite un joueur mort pendant la partie.
  stopuhc:
    description: stop l'uhc en cours.
  say:
    description: parle en broadcast
  saveinv:
    description: sauvegarde l'inventaire de départ.
  enchant:
    description: Ouvre le menu d'enchantement pendant l'édition du kit de départ.
  setgroup:
    description: Définit le nombre de joueurs par groupe/équipe.
  inv:
    description: Permet de visualiser le kit de départ configuré par l'Host.
    aliases: [ starterkit ]
  helpop :
    description: Envoie un message aux hosts
  giveall:
    description: donne des items à tout les joueurs
  rule :
    description : règles
    aliases: [ rules ]
  tr:
    description: Commande principale pour le Tensura UHC
  testdeath:
      description: Ajoute une position de mort fictive sous Limule pour tester Prédateur.
      permission: tensurauhc.admin
  reply:
    description: Répondre à un HelpOp par son numéro
    aliases: [ rhelpop ]